exclude: "^setup/|/static/lib/|/static/src/lib/|.txt"
default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff
        name: Ruff
        args: ["--fix"]
        files: \.py$
      - id: ruff-format
        name: Ruff format
        files: \.py$
