[tool.poetry]
name = "CliFire"
version = "0.1.1"
description = "Minimal CLI framework to build Python commands quickly and elegantly."
authors = ["Roberto Lizana <rober.lizana@gmail.com>"]
readme = "README.md"
packages = [{include = "clifire"}]


[tool.poetry.dependencies]
python = "^3.10"
rich = "^14.0.0"
jinja2 = "^3.1.6"


[tool.poetry.group.dev.dependencies]
nuitka = "^2.7.3"
pytest = "^8.3.5"
coverage = "^7.8.2"
pre-commit = "^4.2.0"
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.14"
mkdocs-static-i18n = "^1.3.0"

[tool.poetry.scripts]
clifire = "clifire.main:main"
fire = "clifire.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
