name: actions

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
      env:
        RYE_TOOLCHAIN_VERSION: '3.12'
        RYE_VERSION: '0.44.0'
        RYE_INSTALL_OPTION: '--yes'

    - name: Install dependencies
      run: |
        rye pin cpython@3.12.2
        rye sync --all-features

    - name: Run pre-commit
      run: rye run pre-commit run --all-files

  test-python-3_8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for Rye
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.2'

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_INSTALL_OPTION: '--yes'

      - name: Install dependencies
        run: |
          rye pin cpython@3.8.2
          rye sync --all-features

      - name: Run unit tests
        run: rye run python -m pytest

  test-python-3_12:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for Rye
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_INSTALL_OPTION: '--yes'

      - name: Install dependencies
        run: |
          rye pin cpython@3.12.2
          rye sync --all-features

      - name: Run unit tests
        run: rye run coverage run -m pytest

      - name: Generate coverage report
        run: rye run coverage xml

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install coveralls
          coveralls
